apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentic-tracker-backend
  namespace: authentic-tracker-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentic-tracker-backend
  template:
    metadata:
      labels:
        app: authentic-tracker-backend
    spec:
      containers:
        - name: app
          image: ghcr.io/krishnarajt/authentic-tracker-backend:git-829f086bf6c9b08556274cfae23f02a9e840f10f
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http

          envFrom:
            - secretRef:
                name: authentic-tracker-backend-env

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
