apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentic-tracker-backend-env
  namespace: authentic-tracker-backend
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authentic-tracker-backend-env
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: apps/authentic-tracker-backend/authentic-tracker-backend/env
